=== TheAwesome1123/Assignment-2/my-app/src/main/java/com/mycompany/app/xml/animalsandproperties/AnimalsAndProperties.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="AnimalsAndProperties">
	<xs:complexType>
					<xs:sequence>
						<xs:element name="Pet">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ID" type="xs:string"/>
									<xs:element name="Type" type="xs:string"/>
									<xs:element name="Name" type="xs:string"/>
									<xs:element name="DateOfBirth" type="xs:string" />
									<xs:element name="Owner_ID" type="xs:string"/>
									<xs:element name="Animal_ID" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="Dog">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ID" type="xs:string"/>
									<xs:element name="Breed" type="xs:string"/>
									<xs:element name="Pet_ID" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="WildAnimal">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ID" type="xs:string"/>
									<xs:element name="Type" type="xs:string"/>
									<xs:element name="Animal_ID" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="HomeContinent">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ID" type="xs:string"/>
									<xs:element name="HomeContinent" type="xs:string"/>
									<xs:element name="WildAnimal_ID" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="DomesticOrWild">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="ID" type="xs:string"/>
									<xs:element name="Type" type="xs:string"/>
									<xs:element name="IsDomesticated" type="xs:string"/>
									<xs:element name="Animal_ID" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== TheAwesome1123/Assignment-2/my-app/src/main/java/com/mycompany/app/xml/animalsandproperties/AnimalsAndProperties.xml
<?xml version="1.0" encoding="UTF-8" ?>

<AnimalsAndProperties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AnimalsAndProperties.xsd">
	<Pet>
		<ID>1</ID>
		<Type>Dog</Type>
		<Name>Max</Name>
		<DateOfBirth>01/05/20</DateOfBirth>
		<Owner_ID>2</Owner_ID>
		<Animal_ID>3</Animal_ID>
	</Pet>
	<Dog>
		<ID>1</ID>
		<Breed>German Shepherd</Breed>
		<Pet_ID>1</Pet_ID>
	</Dog>
	<WildAnimal>
		<ID>2</ID>
		<Type>Wolf</Type>
		<Animal_ID>2</Animal_ID>
	</WildAnimal>
	<HomeContinent>
		<ID>1</ID>
		<HomeContinent>Europe</HomeContinent>
		<WildAnimal_ID>2</WildAnimal_ID>
	</HomeContinent>
	<DomesticOrWild>
		<ID>4</ID>
		<Type>Horse</Type>
		<IsDomesticated>True</IsDomesticated>
		<Animal_ID>5</Animal_ID>
	</DomesticOrWild>
</AnimalsAndProperties>
